/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ExercisePerformance = {
    __kind__: "strength";
    strength: {
        reps: bigint;
        sets: bigint;
    };
} | {
    __kind__: "cardio";
    cardio: {
        duration: bigint;
    };
};
export interface Exercise {
    id: bigint;
    owner: Principal;
    name: string;
    description: string;
    exerciseType: string;
}
export interface Workout {
    id: bigint;
    exerciseIds: Array<bigint>;
    owner: Principal;
    completed: boolean;
    timestamp: Time;
}
export interface WorkoutPerformanceSerializable {
    workoutId: bigint;
    exercisePerformances: Array<[bigint, ExercisePerformance]>;
}
export type Time = bigint;
export interface UserProfile {
    name: string;
    darkMode: boolean;
}
export interface backendInterface {
    addExercise(name: string, exerciseType: string, description: string): Promise<bigint>;
    addExercisePerformance(workoutId: bigint, exerciseId: bigint, performance: ExercisePerformance): Promise<void>;
    areAllExercisesCompleted(workoutId: bigint, exerciseIds: Array<bigint>): Promise<boolean>;
    completeWorkout(id: bigint): Promise<boolean>;
    copyWorkout(originalWorkoutId: bigint): Promise<bigint>;
    createWorkout(exerciseIds: Array<bigint>): Promise<bigint>;
    deleteWorkout(id: bigint): Promise<boolean>;
    getActualSets(workoutId: bigint, exerciseId: bigint): Promise<bigint>;
    getAllExercises(): Promise<Array<Exercise>>;
    getUserProfile(): Promise<UserProfile | null>;
    getWorkoutHistory(): Promise<Array<Workout>>;
    getWorkoutPerformance(workoutId: bigint): Promise<WorkoutPerformanceSerializable | null>;
    initializeAuth(): Promise<void>;
    isExerciseCompleted(workoutId: bigint, exerciseId: bigint): Promise<boolean>;
    markExerciseComplete(workoutId: bigint, exerciseId: bigint): Promise<void>;
    markExerciseIncomplete(workoutId: bigint, exerciseId: bigint): Promise<void>;
    removeExercise(id: bigint): Promise<boolean>;
    saveUserProfile(name: string): Promise<void>;
    toggleDarkMode(): Promise<void>;
    updateActualSets(workoutId: bigint, exerciseId: bigint, actualSets: bigint): Promise<void>;
}
import type { ExercisePerformance as _ExercisePerformance, UserProfile as _UserProfile, WorkoutPerformanceSerializable as _WorkoutPerformanceSerializable } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExercise(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(arg0, arg1, arg2);
            return result;
        }
    }
    async addExercisePerformance(arg0: bigint, arg1: bigint, arg2: ExercisePerformance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercisePerformance(arg0, arg1, to_candid_ExercisePerformance_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercisePerformance(arg0, arg1, to_candid_ExercisePerformance_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async areAllExercisesCompleted(arg0: bigint, arg1: Array<bigint>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.areAllExercisesCompleted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.areAllExercisesCompleted(arg0, arg1);
            return result;
        }
    }
    async completeWorkout(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeWorkout(arg0);
            return result;
        }
    }
    async copyWorkout(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.copyWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.copyWorkout(arg0);
            return result;
        }
    }
    async createWorkout(arg0: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkout(arg0);
            return result;
        }
    }
    async deleteWorkout(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkout(arg0);
            return result;
        }
    }
    async getActualSets(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActualSets(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActualSets(arg0, arg1);
            return result;
        }
    }
    async getAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutHistory(): Promise<Array<Workout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutHistory();
            return result;
        }
    }
    async getWorkoutPerformance(arg0: bigint): Promise<WorkoutPerformanceSerializable | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutPerformance(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutPerformance(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAuth(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAuth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAuth();
            return result;
        }
    }
    async isExerciseCompleted(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isExerciseCompleted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isExerciseCompleted(arg0, arg1);
            return result;
        }
    }
    async markExerciseComplete(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markExerciseComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markExerciseComplete(arg0, arg1);
            return result;
        }
    }
    async markExerciseIncomplete(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markExerciseIncomplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markExerciseIncomplete(arg0, arg1);
            return result;
        }
    }
    async removeExercise(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeExercise(arg0);
            return result;
        }
    }
    async saveUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(arg0);
            return result;
        }
    }
    async toggleDarkMode(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDarkMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDarkMode();
            return result;
        }
    }
    async updateActualSets(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActualSets(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActualSets(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ExercisePerformance_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExercisePerformance): ExercisePerformance {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutPerformanceSerializable_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutPerformanceSerializable): WorkoutPerformanceSerializable {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutPerformanceSerializable]): WorkoutPerformanceSerializable | null {
    return value.length === 0 ? null : from_candid_WorkoutPerformanceSerializable_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workoutId: bigint;
    exercisePerformances: Array<[bigint, _ExercisePerformance]>;
}): {
    workoutId: bigint;
    exercisePerformances: Array<[bigint, ExercisePerformance]>;
} {
    return {
        workoutId: value.workoutId,
        exercisePerformances: from_candid_vec_n7(_uploadFile, _downloadFile, value.exercisePerformances)
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _ExercisePerformance]): [bigint, ExercisePerformance] {
    return [
        value[0],
        from_candid_ExercisePerformance_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    strength: {
        reps: bigint;
        sets: bigint;
    };
} | {
    cardio: {
        duration: bigint;
    };
}): {
    __kind__: "strength";
    strength: {
        reps: bigint;
        sets: bigint;
    };
} | {
    __kind__: "cardio";
    cardio: {
        duration: bigint;
    };
} {
    return "strength" in value ? {
        __kind__: "strength",
        strength: value.strength
    } : "cardio" in value ? {
        __kind__: "cardio",
        cardio: value.cardio
    } : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _ExercisePerformance]>): Array<[bigint, ExercisePerformance]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ExercisePerformance_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExercisePerformance): _ExercisePerformance {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "strength";
    strength: {
        reps: bigint;
        sets: bigint;
    };
} | {
    __kind__: "cardio";
    cardio: {
        duration: bigint;
    };
}): {
    strength: {
        reps: bigint;
        sets: bigint;
    };
} | {
    cardio: {
        duration: bigint;
    };
} {
    return value.__kind__ === "strength" ? {
        strength: value.strength
    } : value.__kind__ === "cardio" ? {
        cardio: value.cardio
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
