/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'exerciseType' : string,
}
export type ExercisePerformance = {
    'strength' : { 'reps' : bigint, 'sets' : bigint }
  } |
  { 'cardio' : { 'duration' : bigint } };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'darkMode' : boolean }
export interface Workout {
  'id' : bigint,
  'exerciseIds' : Array<bigint>,
  'owner' : Principal,
  'completed' : boolean,
  'timestamp' : Time,
}
export interface WorkoutPerformanceSerializable {
  'workoutId' : bigint,
  'exercisePerformances' : Array<[bigint, ExercisePerformance]>,
}
export interface _SERVICE {
  'addExercise' : ActorMethod<[string, string, string], bigint>,
  'addExercisePerformance' : ActorMethod<
    [bigint, bigint, ExercisePerformance],
    undefined
  >,
  'areAllExercisesCompleted' : ActorMethod<[bigint, Array<bigint>], boolean>,
  'completeWorkout' : ActorMethod<[bigint], boolean>,
  'copyWorkout' : ActorMethod<[bigint], bigint>,
  'createWorkout' : ActorMethod<[Array<bigint>], bigint>,
  'deleteWorkout' : ActorMethod<[bigint], boolean>,
  'getActualSets' : ActorMethod<[bigint, bigint], bigint>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getWorkoutHistory' : ActorMethod<[], Array<Workout>>,
  'getWorkoutPerformance' : ActorMethod<
    [bigint],
    [] | [WorkoutPerformanceSerializable]
  >,
  'initializeAuth' : ActorMethod<[], undefined>,
  'isExerciseCompleted' : ActorMethod<[bigint, bigint], boolean>,
  'markExerciseComplete' : ActorMethod<[bigint, bigint], undefined>,
  'markExerciseIncomplete' : ActorMethod<[bigint, bigint], undefined>,
  'removeExercise' : ActorMethod<[bigint], boolean>,
  'saveUserProfile' : ActorMethod<[string], undefined>,
  'toggleDarkMode' : ActorMethod<[], undefined>,
  'updateActualSets' : ActorMethod<[bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];