/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExercisePerformance = IDL.Variant({
  'strength' : IDL.Record({ 'reps' : IDL.Nat, 'sets' : IDL.Nat }),
  'cardio' : IDL.Record({ 'duration' : IDL.Nat }),
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'exerciseType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'darkMode' : IDL.Bool,
});
export const Time = IDL.Int;
export const Workout = IDL.Record({
  'id' : IDL.Nat,
  'exerciseIds' : IDL.Vec(IDL.Nat),
  'owner' : IDL.Principal,
  'completed' : IDL.Bool,
  'timestamp' : Time,
});
export const WorkoutPerformanceSerializable = IDL.Record({
  'workoutId' : IDL.Nat,
  'exercisePerformances' : IDL.Vec(IDL.Tuple(IDL.Nat, ExercisePerformance)),
});

export const idlService = IDL.Service({
  'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addExercisePerformance' : IDL.Func(
      [IDL.Nat, IDL.Nat, ExercisePerformance],
      [],
      [],
    ),
  'areAllExercisesCompleted' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Bool],
      ['query'],
    ),
  'completeWorkout' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'copyWorkout' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'createWorkout' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'deleteWorkout' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getActualSets' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getWorkoutHistory' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  'getWorkoutPerformance' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(WorkoutPerformanceSerializable)],
      ['query'],
    ),
  'initializeAuth' : IDL.Func([], [], []),
  'isExerciseCompleted' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
  'markExerciseComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'markExerciseIncomplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'removeExercise' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveUserProfile' : IDL.Func([IDL.Text], [], []),
  'toggleDarkMode' : IDL.Func([], [], []),
  'updateActualSets' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExercisePerformance = IDL.Variant({
    'strength' : IDL.Record({ 'reps' : IDL.Nat, 'sets' : IDL.Nat }),
    'cardio' : IDL.Record({ 'duration' : IDL.Nat }),
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'exerciseType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'darkMode' : IDL.Bool });
  const Time = IDL.Int;
  const Workout = IDL.Record({
    'id' : IDL.Nat,
    'exerciseIds' : IDL.Vec(IDL.Nat),
    'owner' : IDL.Principal,
    'completed' : IDL.Bool,
    'timestamp' : Time,
  });
  const WorkoutPerformanceSerializable = IDL.Record({
    'workoutId' : IDL.Nat,
    'exercisePerformances' : IDL.Vec(IDL.Tuple(IDL.Nat, ExercisePerformance)),
  });
  
  return IDL.Service({
    'addExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addExercisePerformance' : IDL.Func(
        [IDL.Nat, IDL.Nat, ExercisePerformance],
        [],
        [],
      ),
    'areAllExercisesCompleted' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Bool],
        ['query'],
      ),
    'completeWorkout' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'copyWorkout' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'createWorkout' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'deleteWorkout' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getActualSets' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getWorkoutHistory' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
    'getWorkoutPerformance' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(WorkoutPerformanceSerializable)],
        ['query'],
      ),
    'initializeAuth' : IDL.Func([], [], []),
    'isExerciseCompleted' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
    'markExerciseComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'markExerciseIncomplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'removeExercise' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveUserProfile' : IDL.Func([IDL.Text], [], []),
    'toggleDarkMode' : IDL.Func([], [], []),
    'updateActualSets' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };